spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usercenter?useUnicode=true&characterEncoding=utf8
    username: root
    password: test
    druid:
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
  redis:
    host: localhost
    port: 6379
  application:
        name: user_center

server:
  port: 8090

mybatis:
  configLocation: classpath:mybatis/mybatis-config.xml
  mapperLocations: classpath:mybatis/mapper/**/*.xml

debug: true

logging:
  level:
    com:
      example:
        usercenter:
          sys:
            dao: debug